#PIPELINE TERRAFORM
name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Executar o terraform apply ?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'